sodu: required    #this says "hey travis, we need superuser level permissions in order to execute this build"

# telling travis that we are using docker as a service
services: 
  - docker

# series of commands that get executed before our tests are run 
before_install: 
  - docker build -t kartik0912/docker-react -f Dockerfile.dev . 

# contains all the commands required to run our test suite 
script: 
  - docker run -e CI=true kartik0912/docker-react npm run test

# to configure travis CI to deploy our application after the tests are run
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"    
  app: "docker-react"
  env: "Docker-react"
  bucket_name: "elasticbeanstalk-us-east-1-659311134658"
  bucket_path: "docker-react"
  on: 
    branch: main
  access_key_id: "AKIAZTAQBQ7BCJPLN2N7"
  secret_access_key: "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"